version: '2'
services:
    nginx:
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./conf:/etc/nginx/conf
            - ./logs:/nginx/logs
            - ./private:/etc/nginx/private
        restart: always
        external_links:
            - redbutton_ionic_1 
